version: '3'

## - TODO ===================
## - TODO containers:
## - TODO ===================
## - TODO nats
## - TODO nats-wanbus
## - TODO ===================
## - TODO 

services:
  nats-wanbus:
    environment:
      - PUBNUB_SUBSCRIBE_KEY=demo
      - PUBNUB_PUBLISH_KEY=demo
      - PUBNUB_SECRET_KEY=demo
      - PUBNUB_CHANNEL=channels.*
      - NATS_SUBJECT=channels.*
      - NATS_HOST=nats
      - NATS_USER=
      - NATS_PASSWORD=
      - NATS_AUTH_TOKEN=
    build: .
    image: nats-wanbus
    restart: on-failure
    links:
      - nats
    depends_on:
      - nats

  nats:
    image: nats
    ports:
      - "4222:4222"
