version: '3'

services:
  nats-wanbus:
    environment:
      - PUBNUB_PUBLISH_KEY=pub-c-6b57a39e-79e7-4d1d-926e-5c376a4cb021
      - PUBNUB_SUBSCRIBE_KEY=sub-c-df3799ee-704b-11e9-8724-8269f6864ada
      - PUBNUB_SECRET_KEY=sec-c-YWY3NzE0NTYtZTBkMS00YjJjLTgxZDQtN2YzOTY0NWNkNGVk
      - PUBNUB_CHANNEL_ROOT=channels
      - PUBNUB_CHANNEL=*
      - NATS_SUBJECT=*
      - NATS_HOST=nats
      - NATS_USER=
      - NATS_PASSWORD=
      - NATS_AUTH_TOKEN=
    build: .
    image: nats-wanbus
    restart: on-failure
    links:
      - nats
    depends_on:
      - nats

  nats:
    image: nats
    ports:
      - "4222:4222"
