[package]
name = "nats-bridge"
version = "0.1.0"
authors = ["Stephen Blum <blum.stephen@gmail.com>"]
edition = "2018"

[dependencies]
nats = "0.3.2"
actix-web = "0.7.19"
actix-rt = "0.2.2"
failure = "^0.1"
failure_derive = "^0.1"
openssl = { version = "0.10", features = ["vendored"] }

[[bin]]
name = "nats-bridge"
path = "src/main.rs"
