[package]
name = "nats-bridge"
version = "0.1.0"
authors = ["Stephen Blum <blum.stephen@gmail.com>"]
edition = "2018"

[dependencies]
nats = "0.3.2"
hyper = "0.12"
failure = "^0.1"
failure_derive = "^0.1"

[[bin]]
name = "nats-bridge"
path = "src/main.rs"
