[package]
name = "kafka-bridge"
version = "0.2.1"
authors = ["Stephen Blum <blum.stephen@gmail.com>"]
edition = "2018"
readme = "readme.md"

[features]
nightly = []

[dependencies]
json = "0.12"
percent-encoding = "2.1.0"
rdkafka = "0.24"
