[package]
name = "nats-bridge"
version = "0.1.0"
authors = ["Stephen Blum <blum.stephen@gmail.com>"]
edition = "2018"
readme = "readme.md"

[features]
nightly = []

[dependencies]
json = "*"
# openssl = { version = "0.10", features = ["vendored"] }
native-tls = "0.2.2"
failure = "^0.1"
failure_derive = "^0.1"
