---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/zookeeper_jass.conf -Dzookeeper.authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider"

    volumes:
      - './zookeeper_jass.conf:/etc/kafka/zookeeper_jass.conf'
    network_mode: host
    hostname: kafka.confluent.io
    domainname: ""
    extra_hosts:
    - "kafka.confluent.io:127.0.0.1"

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    ports:
      - '9092:9092'
      - '9094:9094'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka.confluent.io:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka.confluent.io:9092,OUTSIDE://kafka.confluent.io:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jass.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:SASL_SSL,OUTSIDE:SASL_SSL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SSL_ENABLED_PROTOCOLS: TLSv1.2
      KAFKA_SSL_PROTOCOL: TLSv1.2
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: HTTPS
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/node.ts
      KAFKA_SSL_TRUSTSTORE_PASSWORD: secret
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/node.ks
      KAFKA_SSL_KEYSTORE_PASSWORD: secret
      KAFKA_SSL_CLIENT_AUTH: required

    network_mode: host
    hostname: kafka.confluent.io
    domainname: ""
    extra_hosts:
    - "kafka.confluent.io:127.0.0.1"

    volumes:
      - './kafka_server_jass.conf:/etc/kafka/kafka_server_jass.conf'
      - './secrets/kafka/:/etc/kafka/secrets/'

  kafka-create-topics:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    depends_on:
      - zookeeper
      - kafka
    network_mode: host
    hostname: kafka.confluent.io
    domainname: ""
    extra_hosts:
    - "kafka.confluent.io:127.0.0.1"
    volumes:
      - './kafka_client_jass.conf:/etc/kafka/kafka_client_jass.conf'
      - './kafka-sample-generator.sh:/bin/kafka-sample-generator.sh'
      - './cub.properties:/etc/kafka/cub.properties'
      - './client.properties:/etc/kafka/client.properties'
      - './secrets/producer/:/etc/kafka/secrets'
    command: "/bin/kafka-sample-generator.sh"
    environment:
      KAFKA_TOPIC: topic
      KAFKA_BROKER: kafka.confluent.io
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_client_jass.conf"