---
version: '2'
services:
  #kafka-edge-messaging-platform:
  #  environment:
  #    PUBNUB_PUBLISH_KEY: pub-c-6b57a39e-79e7-4d1d-926e-5c376a4cb021 
  #    PUBNUB_SUBSCRIBE_KEY: sub-c-df3799ee-704b-11e9-8724-8269f6864ada 
  #    PUBNUB_SECRET_KEY: sec-c-YWY3NzE0NTYtZTBkMS00YjJjLTgxZDQtN2YzOTY0NWNkNGVk 
  #    PUBNUB_CIPHER_KEY: PaSsWoRd     ## encryption key
  #    PUBNUB_CHANNEL_ROOT: topics     ## topics.
  #    PUBNUB_CHANNEL: "*"             ## topics
  #    KAFKA_TOPIC_ROOT: topics        ## topics <-> topics.*
  #    KAFKA_TOPIC: topic              ## topics <-> topics.*
  #    KAFKA_GROUP:  
  #    KAFKA_PARTITION: 0  
  #    KAFKA_BROKERS: kafka:9092       ## comma separated list
  #  build:
  #    context: ..
  #    dockerfile: kafka/dockerfile
  #  image: kafka-edge-messaging-platform
  #  restart: on-failure
  #  depends_on:
  #    - zookeeper
  #    - kafka
  #    - kafka-create-topics

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    hostname: kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB  
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-create-topics:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    depends_on:
      - zookeeper
      - kafka
    hostname: kafka-create-topics
    volumes:
      - './kafka-sample-generator.sh:/bin/kafka-sample-generator.sh'
    command: "/bin/kafka-sample-generator.sh"
    environment:
      KAFKA_TOPIC: topic
      KAFKA_BROKER: kafka
